---
# Example Playbook: Create a KubeVirt VirtualMachineSnapshot
- name: Create KubeVirt Snapshot
  hosts: localhost
  gather_facts: yes
  vars:
    vm_name: web-server-01
    vm_namespace: default
    kubeconfig: ~/.kube/config
    snapshot_name: "backup-{{ ansible_date_time.epoch }}"

  tasks:
    - name: Create snapshot
      ansible.builtin.include_role:
        name: ocp_virt_snapshot

    - name: Display snapshot information
      ansible.builtin.debug:
        msg:
          - "Snapshot created successfully!"
          - "VM: {{ snapshot_info.vm_name }}"
          - "Namespace: {{ snapshot_info.vm_namespace }}"
          - "Snapshot Name: {{ snapshot_info.snapshot_name }}"
          - "Snapshot UID: {{ snapshot_info.snapshot_uid }}"
          - "Status: {{ snapshot_info.snapshot_phase }}"
          - "Disks Included: {{ snapshot_info.vm_disks_count }}"
          - "Created: {{ snapshot_info.created_at }}"
      when: snapshot_info is defined
